# deployment.yaml
apiVersion: apps/v1 # The API resource where this workload resides
kind: Deployment # The kind of workload we're creating
metadata:
  name: brownbag-website # This will be the name of the deployment
spec:
  selector: # Define the wrapping strategy
    matchLabels: # Match all pods with the defined labels
      app: brownbag-website # Labels follow the `name: value` template

  template: # This is the template of the pod inside the deployment
    metadata: # Metadata for the POD
      labels:
        app: brownbag-website
    spec:
      containers: # Here we define all containers
        - image: brownbagacr.azurecr.io/brownbag-website
          name: brownbag-website
          resources:
            requests: # Minimum amount of resources requested
              cpu: 100m
              memory: 128Mi
            limits: # Maximum amount of resources requested
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 80 # This container exposes port 80
              name: http # We named that port "http" so we can refer to it later




